version: 0.2

phases:
  build:
    commands:
      - echo Packaging Lambda...
      - mkdir package
      - cp lambda_function.py package/
      - cd package
      - zip -r ../function.zip .

artifacts:
  files:
    - function.zip
